# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
