# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170224_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
