# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170227_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
